
#
# Upload to staging repo OSSRH

name: Upload to staging

on:
  push:
    tags: '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      KEYID: "${{ secrets.KEYID }}"
      PASSWORD: "${{ secrets.PASSWORD }}"
      KEY: "${{ secrets.KEY }}"
      OSSRH_USERNAME: "${{ secrets.OSSRH_USERNAME }}"
      OSSRH_PASSWORD: "${{ secrets.OSSRH_PASSWORD }}"
      SONATYPE_STAGING_PROFILE_ID: "${{ secrets.SONATYPE_STAGING_PROFILE_ID }}"
      VERSION: "${{ secrets.VERSION }}"

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests
      run: git submodule update --init --recursive && ./gradlew assemble && ./gradlew uploadArchives
